refreshRate = 10
apiURLFile = "api_url.txt"
rumbleTimestampFormat = "%Y-%m-%dT%H:%M:%S+00:00"

durationDefault = 60

[APIHeaders]
User-Agent = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36"

[durationOptions]
"1 minute" = 60
"5 minutes" = 300
"10 minutes" = 600
